name: Commit lint

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
