name: Cron test

on:
- push

jobs:
  test:
    env:
      PULP_USERNAME: ${{ secrets.PULP_USERNAME}}
      PULP_PASSWORD: ${{ secrets.PULP_PASSWORD}}
      PULP_LICENSE_URL: ${{ secrets.PULP_LICENSE_URL}}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: License
        id: license
        run: |
          LICENSE=$(curl -s -L -u"$PULP_USERNAME:$PULP_PASSWORD" "$PULP_LICENSE_URL")
          echo "::add-mask::$LICENSE"
          echo "::set-output name=LICENSE::$LICENSE"

      - name: Add mask
        run: |
          echo ::add-mask::${{ steps.license.outputs.LICENSE }}

      - uses: gliech/create-github-secret-action@v1
        with:
          name: MY_SECRET_NAME
          value: ${{ steps.license.outputs.LICENSE }}
          pa_token: ${{ secrets.PAT }}

      - name: Update secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: MY_SECRET_NAME2
          value: ${{ steps.license.outputs.LICENSE }}
          # repository: hmanzur/actions-set-secret
          token: ${{ secrets.PAT }}
